### ISSUE TITLE
Abweichung Werte Socio_data

### ISSUE THREAD

**Issue by Lwinkeler** [quarree100/q100_abm#14]
Verteilung der Werte von (mind.) **PBC_XY** ist fehlerhaft:

*Wie die Daten verteilt sind:*
<img width="152" alt="Bildschirmfoto 2021-12-15 um 10 48 38" src="https://user-images.githubusercontent.com/70899694/146163479-c90b6d78-8fbd-436e-9e4b-55bde1ad0b35.png">

*Wie die Daten verteilt sein sollten:*
<img width="548" alt="Bildschirmfoto 2021-12-15 um 10 44 08" src="https://user-images.githubusercontent.com/70899694/146163491-e66abfc3-de02-40be-b5fc-f5ed4e3a0c39.png">

Es wird nicht die volle Breite der Quartile ausgeschöpft. Bitte prüfen.

**Comment by phiola** [comment]
Ah cool. Wenn man die Issue-Nummer im commit nennt, wird der beim mergen automatisch geschlossen
