### ISSUE TITLE
"Hard" coded globale Variablen

### ISSUE THREAD

**Issue by lwinkeler** [quarree100/q100_abm#67]
siehe
[quarree100/qScope_frontend/#35](https://github.com/quarree100/qScope_frontend/issues/35)

- [x] Anlegen einer csv-Datei, welche die entsprechenden globalen Parameter festlegt
- [x] Auslesen der csv-Datei in GAMA für die entsprechenden Variablen

**Comment by lwinkeler** [comment]
to be verified by @dunland

**Comment by dunland** [comment]
scheint ohne Reibungen zu laufen!
