### ISSUE TITLE
Sende step via UDP zu Infoscreen zur Statusanzeige

### ISSUE THREAD

**Issue by dunland** [quarree100/q100_abm#80]
Since the Simulation takes so long, it'd be good to have status information about it on the infoscreen.
Maybe by receiving the current step num from GAMA via UDP!

**GAMA** @phiola 
https://gama-platform.org/wiki/UsingNetwork#creation-of-a-network-agent
send via localhost:8082

**Infoscreen** @dunland @kazux2
receive message, implement display (percentage / status bar)

**Comment by dunland** [comment]
a json string should be transmitted using this form:
`{'step' : step}` --> e.g. {'step' : 500}
I think sending this every 100 steps should be enough, cause this roughly represents a 1% step of the simulation.

**Comment by kazux2** [comment]
implemented https://github.com/quarree100/qScope_infoscreen/pull/25

**Comment by dunland** [comment]
- [ ] @kazux2 the infoscreen does not seem to receive the data properly. let's take care of this today!

**Comment by dunland** [comment]
all done!
