### ISSUE TITLE
export individual energy_prices

### ISSUE THREAD

**Issue by dunland** [quarree100/q100_abm#82]
Moin! Ich hatte gehört, sowas könnt ihr berechnen...

zur Darstellung von gebäudespezifischen Energiekosten muss GAMA diese noch auszuspucken lernen, und zwar bestenfalls ca. so:
``` java
export_file <- (timestamp = "") ? "../data/outputs/output/energy_prices/energy_prices_" + id + ".csv" : "../data/outputs/output_" + timestamp + "/energy_prices/energy_prices_" + id + ".csv";
save [cycle, current_date, id, oil_price, gas_price, power_price]
```

**Comment by dunland** [comment]
**without scaling:**
select 1 building → make decision →send to gama → calculate **real** energy prices → export individual costs → plot **real** values

**with scaling:**
select 1 building → make decision → apply decisions cluster → send whole cluster to gama → calculate **real** energy prices → export individual costs → plot average values

**Comment by dunland** [comment]
...ich bräuchte das jetzt relativ dringend, um aus den Daten dann plots machen zu können... bis wann kann ich damit rechnen?

**Comment by lwinkeler** [comment]
Spätestens morgen Abend.

**Comment by dunland** [comment]
alles erledigt!
