### ISSUE TITLE
Berechnung Wärmebedarf überarbeiten

### ISSUE THREAD

**Issue by phiola** [quarree100/q100_abm#89]
Aktuelle wird der Wärmebedarf eines Haushaltes folgendermaßen berechnet:
```
action calculate_consumption { // consumption divided by building type

		if (self.house.type = "EFH") and (self.house.mod_status = "u") {
			my_heat_consumption <- my_floor_area * self.house.spec_heat_consumption * heat_consumption_exist_EFH_change_rate / 12;
		}
		else if (self.house.type = "EFH") and (self.house.mod_status = "s") {
			my_heat_consumption <- my_floor_area * self.house.spec_heat_consumption * heat_consumption_new_EFH_change_rate / 12;
		}
		else if (self.house.type = "MFH") and (self.house.mod_status = "u") {
			my_heat_consumption <- my_floor_area * self.house.spec_heat_consumption * heat_consumption_exist_MFH_change_rate / 12;
		}
		else if (self.house.type = "EFH") and (self.house.mod_status = "s") {
			my_heat_consumption <- my_floor_area * self.house.spec_heat_consumption * heat_consumption_new_MFH_change_rate / 12;
		}
		my_power_consumption <- my_floor_area * self.house.spec_power_consumption * power_consumption_change_rate / 12; // tatsaechlich kwh/qm spez stromverbrauch?
```
Die aus den Agora-Daten berechneten Änderungsraten (`heat_[...]_change_rate`) beziehen sich allerdings nicht auf den Ursprungswert, sondern immer auf das Vorjahr. Es müsste also in jedem Jahr mit allen vorherigen Werten multipliziert werden. Alternativ könnte die csv-Datei so angepasst werden, dass sich die Änderungsraten immer auf den n=0-Wert beziehen. 

Auch entsteht aktuell durch die Sanierung keine Energieeinsparung, da in der momentanen Berechnung nur die Verlaufskurve relativen Veränderung gewechselt wird, nicht aber von einem geringeren Grundverbrauch ausgegangen wird. Dabei kann der Verbrauch sogar steigen. (Siehe markierte Zeile)
![Änderungsraten Wärmeverbrauch](https://user-images.githubusercontent.com/84175028/190118049-3d545382-f40b-4cf4-894f-dca388572253.png)

**Comment by phiola** [comment]
To Do:

- [ ] Wird action `modernize` vom Qscope aufgerufen?

**Comment by lwinkeler** [comment]
#76
