### ISSUE TITLE
Umweltengagement / Environmental engagement

### ISSUE THREAD

**Issue by lwinkeler** [quarree100/q100_abm#91]
siehe auch https://github.com/quarree100/qScope_infoscreen/issues/23#issuecomment-1229962529

Die Variable bzw. Aktion soll (mindestens im Infoscreen für Teilnehmende des workshops) nicht länger `environmental engagement` / `Umweltengagement`heißen

-> stattdessen: `Energiesparen`

- [x] Austausch der Begrifflichkeit

**Comment by dunland** [comment]
Bezugnehmend auf https://github.com/quarree100/qScope_infoscreen/issues/23#issuecomment-1229962529 möchte ich nochmal nachhaken, ob der Wert denn nun ein bool bleibt oder nicht..

**Comment by dunland** [comment]
ist erledigt!
