### ISSUE TITLE
kleine Analyse der Gebäude-Verbrauchsdaten

### ISSUE THREAD

**Issue by lwinkeler** [quarree100/q100_abm#92]
@dunland schrieb:

> Moin,
> 
> wir hatten ja die Befürchtung, dass die (geclusterten) Verbrauchsdaten der Gebäude auf dem Q-Scope falsch ausgerechnet oder dargestellt werden. Dem ist nicht so! Ich habe die Ergebnisse noch mal mit den Katasterdaten verglichen, und die Cluster-Daten weichen tatsächlich nur minimal von den Katasterdaten ab (aus den Clustern ergibt sich, so wie sie jetzt gewählt sind, ein Durchschnittsverbrauch, der im Mittel bei 10-12kWh Unterschied zum tatsächlichen Gebäudewert liegt). Das könnt ihr auch der angefügten Tabelle entnehmen.
> 
- [x] Es ist also vielmehr so, dass im Kataster die Verbrauchsdaten teilweise enorm hoch sind (Beispiel Neue Heimat 22: ca. 640 kWh Wärme/m²). Da gibt es also sicher noch was zu diskutieren / prüfen

**Comment by dunland** [comment]
Ich wollte gerne noch mal rausfinden, ob wir mit dieser Methode des Clustern nach Energieträger und Verbrauch zufrieden sind.
Zusammengefasst sehen wir: je Größer das Toleranzinterval, in dem sich Referenzgebäude aufhalten dürfen, desto "ähnlicher" werden alle Gebäude - logisch! Wie man jetzt den passenden Rahmen auswählt, weiß ich überhaupt nicht. Ob diese Methode unsere Daten sinnvoll verschleiert weiß ich auch nicht, denn deutliche relative Unterschiede zwischen den Gebäuden lassen sich selbstverständlich noch aufdecken...

  | cluster_size | spec_heat_consumption | avg_spec_heat_consumption | spec_power_consumption | avg_spec_power_consumption
-- | -- | -- | -- | -- | --
count | 140.000000 | 140.000000 | 140.000000 | 140.000000 | 140.000000
mean | 12.321429 | 217.435523 | 217.554814 | 35.387948 | 34.871596
std | 8.401154 | 101.175756 | 93.803518 | 23.339964 | 20.051225
min | 2.000000 | 20.702610 | 34.946040 | 0.142860 | 6.603895
25% | 4.000000 | 159.589323 | 160.126731 | 18.822215 | 18.377012
50% | 12.000000 | 201.954410 | 194.666699 | 32.118345 | 33.334228
75% | 20.250000 | 260.633915 | 255.085203 | 45.545290 | 43.712982
max | 28.000000 | 640.166190 | 586.602200 | 178.524550 | 141.793440

für die Wärme allein sieht die vollständige Liste (Verbrauch absolut vs gemittelt aus cluster) so aus:

id | type | spec_heat_consumption | avg_spec_heat_consumption
-- | -- | -- | --
1.02 | EFH | 166.14386 | 179.81150866666667
1.04 | EFH | 230.0 | 230.0
1.05 | EFH | 230.0 | 230.0
1.06 | EFH | 156.29499 | 134.77024
1.08 | EFH | 88.71847 | 102.48875210526316
1.09 | EFH | 161.62654 | 165.83974454545458
1.10 | EFH | 230.0 | 230.0
1.11 | MFH | 278.04614 | 274.8478785714286
1.12 | EFH | 151.01156 | 166.52176529411764
1.13 | EFH | 230.0 | 230.0
2.01 | EFH | 235.61121 | 227.0535127777778
2.02 | EFH | 153.41424 | 158.38243280000003
2.03 | EFH | 385.58252 | 381.96153749999996
2.04 | EFH | 134.67302 | 134.8901474074074
2.05 | EFH | 163.99621 | 161.22689642857145
2.06 | EFH | 130.86899 | 148.72785823529412
2.07 | EFH | 135.86133 | 147.10931
2.08 | EFH | 241.70314 | 230.63387199999997
2.09 | EFH | 372.27692 | 368.616375
2.10 | EFH | 187.70325 | 176.725586875
2.11 | EFH | 41.27573 | 88.56853000000001
2.12 | EFH | 417.88618 | 423.1029433333333
2.13 | EFH | 260.26423 | 256.96501470588237
2.14 | EFH | 255.05259 | 246.9644785714286
2.15 | EFH | 365.66536 | 352.412284
2.16 | EFH | 118.79579 | 121.12165347826085
2.17 | EFH | 126.12907 | 150.02850933333332
2.18 | EFH | 123.39785 | 134.12615035714288
2.19 | EFH | 191.44105 | 190.37571272727274
2.20 | EFH | 210.79162 | 202.8766896153846
2.21 | EFH | 261.74297 | 265.49980999999997
3.01 | EFH | 230.0 | 230.0
3.03 | EFH | 493.69393 | 432.87735
3.04 | MFH | 170.0 | 170.0
3.05 | MFH | 364.95583 | 355.39337333333333
3.06 | MFH | 200.24337 | 193.92922499999997
3.07 | MFH | 262.52214 | 254.458599
3.08 | MFH | 320.50373 | 330.905008
3.09 | MFH | 358.71209 | 345.674545
3.10 | MFH | 85.18346 | 109.5947375
3.12 | MFH | 136.23941 | 133.8646128
4.01 | EFH | 281.19595 | 283.132795
4.03 | EFH | 372.06077 | 344.459554
4.05 | EFH | 293.65666 | 319.5964266666667
4.06 | EFH | 492.59193 | 497.1567566666667
4.07 | EFH | 160.0 | 221.25
4.08 | EFH | 166.80037 | 176.75260125
4.09 | EFH | 97.86622 | 111.504015
4.10 | EFH | 259.81115 | 246.90672
4.11 | EFH | 213.2772 | 227.49016999999998
4.12 | EFH | 198.02225 | 182.573935625
4.13 | EFH | 144.15833 | 158.69181888888886
4.14 | EFH | 160.0 | 167.5
4.15 | EFH | 164.38239 | 169.3747272727273
4.16 | EFH | 180.20505 | 182.704330625
4.17 | EFH | 201.65354 | 191.52344562500002
4.18 | EFH | 157.61206 | 156.35249884615385
4.19 | EFH | 221.35674 | 219.9097544
4.20 | EFH | 299.45451 | 281.68130833333333
4.21 | EFH | 186.97284 | 187.07221727272727
4.22 | EFH | 160.0 | 155.83289444444443
4.23 | EFH | 640.16619 | 586.6022
4.24 | EFH | 140.48691 | 144.03394555555556
4.25 | EFH | 91.67687 | 106.85249294117646
4.26 | EFH | 43.7699 | 64.29686428571429
4.27 | EFH | 250.74146 | 247.9985931578947
4.28 | EFH | 311.98585 | 295.52728875
4.29 | EFH | 293.07185 | 296.94268000000005
4.30 | EFH | 236.01355 | 230.80269590909091
4.31 | EFH | 113.24549 | 134.77024
5.01 | MFH | 170.0 | 167.5
5.03 | MFH | 73.12273 | 90.58488153846154
5.04 | MFH | 170.0 | 170.0
5.05 | MFH | 249.22812 | 241.64139941176467
5.06 | MFH | 170.0 | 161.56304047619045
5.07 | MFH | 170.0 | 210.0
5.08 | MFH | 193.19703 | 189.67999666666668
5.09 | MFH | 446.94825 | 409.50451
5.10 | MFH | 215.54473 | 206.89994846153846
5.11 | MFH | 177.68504 | 167.60058545454544
5.12 | MFH | 298.94988 | 288.45603200000005
5.14 | MFH | 327.39636 | 410.54514500000005
5.15 | MFH | 170.0 | 176.46877285714282
6.01 | MFH | 170.0 | 166.38184458333333
6.02 | MFH | 170.0 | 160.60503454545454
6.03 | MFH | 170.0 | 175.30540000000002
6.04 | MFH | 170.0 | 164.38016909090908
6.06 | MFH | 533.03821 | 512.81507
6.07 | MFH | 170.0 | 167.5
6.08 | MFH | 88.08947 | 104.53757375
6.09 | MFH | 171.49743 | 174.6870675
6.10 | MFH | 201.44834 | 186.37856499999998
7.06 | MFH | 40.36561 | 59.12813166666667
7.07 | EFH | 230.0 | 230.0
7.08 | EFH | 96.19743 | 116.507456
7.09 | EFH | 230.0 | 225.208848
7.10 | EFH | 262.80724 | 262.93351058823527
7.11 | EFH | 131.60836 | 133.8646128
7.12 | EFH | 300.82905 | 286.45658083333336
7.13 | EFH | 230.0 | 230.0
7.14 | EFH | 158.35729 | 147.10931
7.15 | EFH | 306.27471 | 289.70341
7.16 | EFH | 241.44586 | 231.26454999999999
7.17 | EFH | 465.84013 | 458.7727466666667
7.18 | EFH | 230.0 | 230.0
7.20 | EFH | 210.97545 | 173.41839
7.21 | EFH | 112.92122 | 119.17280999999998
7.22 | EFH | 230.0 | 230.0
7.23 | EFH | 230.0 | 230.0
7.24 | EFH | 312.36801 | 296.50948625
7.26 | EFH | 269.60733 | 270.327326
7.27 | EFH | 230.0 | 230.0
7.28 | EFH | 147.13783 | 144.63671333333335
7.29 | EFH | 230.0 | 230.0
7.30 | EFH | 97.42794 | 110.99357411764707
7.31 | EFH | 96.11566 | 111.31320499999998
7.32 | EFH | 202.25528 | 188.8360315789474
7.33 | EFH | 188.65711 | 184.15395958333332
7.34 | EFH | 328.94737 | 312.9569788888889
7.35 | MFH | 91.72186 | 106.85249294117646
7.38 | MFH | 20.70261 | 34.94604
7.39 | EFH | 230.0 | 230.0
7.40 | MFH | 262.25194 | 270.3570266666666
7.41 | MFH | 175.61739 | 178.509135
7.43 | MFH | 331.59772 | 344.119725
7.44 | EFH | 420.98389 | 417.4165075
7.45 | EFH | 221.69185 | 221.80728499999995
7.47 | EFH | 316.56024 | 296.94268000000005
7.48 | EFH | 133.04899 | 131.002520625
7.50 | EFH | 230.0 | 230.0
7.52 | EFH | 230.0 | 230.0
7.53 | EFH | 205.16408 | 195.40417391304345
7.54 | EFH | 136.24683 | 134.8901474074074
7.55 | EFH | 203.44679 | 197.37986799999996
7.56 | MFH | 169.53986 | 166.586468
7.57 | EFH | 111.48009 | 120.18740952380952
7.59 | EFH | 292.8476 | 283.5928530769231
7.63 | EFH | 170.81082 | 177.22420583333337
7.64 | MFH | 170.0 | 167.5
7.65 | EFH | 240.71141 | 229.01308285714282

**Comment by lwinkeler** [comment]
Bedeutet, dass das resultierende TODO an der Stelle folgendes ist?

- [ ] Festlegen einer nachvollziehbaren & begründeten Clustergröße

> Ob diese Methode unsere Daten sinnvoll verschleiert weiß ich auch nicht, denn deutliche relative Unterschiede zwischen den Gebäuden lassen sich selbstverständlich noch aufdecken...

Da würde ich auf das Gespräch mit David Sauss verweisen; der hatte darauf hingewiesen, dass der einzige kritische Punkt, das Verwenden der exakten Daten sei. Relative Unterschiede oder grobe Werte seien kein Problem. Besonders auch, da die Häuser (nach Prüfung) den Standard-Werten, wie man sie überall im Internet findet, entsprechen und damit quasi offensichtlich zuzuordnen sei, wie die groben Daten dieser Häuser aussehen.

**Comment by lwinkeler** [comment]
Ich habe die Katasterdatei nochmal geprüft. Leider finden sich zu den rot markierten Häusern keine speziellen weiteren Angaben oder Notizen, die darauf schließen lassen, weshalb die Markierung genau hier stattgefunden hat (außer, dass es die 11 Häuser mit den schlechtesten Verbrauchswerten sind). Darüber hinaus ist jedoch spannend, dass verschiedene Häuser-Arten vertreten sind, also sowohl NWG als auch EFH und MFH.

_______________

Das bringt mich zum folgenden Punkt: Zur Vergleichbarkeit im Workshop ist der absolute Gesamtverbrauch eines Gebäudes pro Jahr m.E. sinnvoll. Die/der spezifische Wärme/Strom ist ein Wert der möglicherweise erneut schwer mit Fachfremden zu diskutieren ist.
Demgegenüber steht, dass das Clustern der flächenspezifischen Werte den Vorteil bietet, dass Häuser mit ähnlichem Modernisierungsstatus unabhängig von der Größe miteinander verglichen werden können. Außerdem umgeht man das Problem, dass bspw. ein großes modernisiertes Haus im gleichen Cluster landet, wie ein kleines ungedämmtes (da der absolute Verbrauch dadurch in ähnlichen Bereichen sein könnte).

- Eine Möglichkeit könnte sein, die Häuser nach den spezifischen Verbräuchen zu clustern, dennoch aber die absoluten Werte am Infoscreen darzustellen.

**Comment by lwinkeler** [comment]
## Festlegen einer nachvollziehbaren & begründeten Clustergröße

Wir ordnen die Häuser eh bereits nach dem spezifischen Wärmeverbrauch ein. Die gleiche Einordnung erfolgt ebenfalls bei der Energieeffizienzklasse von Häusern nach folgenden Gebäudestandards:

**Energieeffizienzklasse Endenergie [(kWh/(m2•a)]**

- A+ < 30
- A < 50
- B < 75
- C < 100
- D < 130
- E < 160
- F < 200
- G < 250
- H > 250

Unsere Katasterdaten sind natürlich nicht verhaltensbereinigt, dass die Einstufung demnach exakt zutrifft, muss infrage gestellt werden. Für die Erstellung der Cluster dürfte es aber passen 👍 

Verweise: Verbraucherzentrale -> [Effizienzklassen und Vergleichswerte](https://www.verbraucherzentrale.de/wissen/energie/energetische-sanierung/energieausweis-was-sagt-dieser-steckbrief-fuer-wohngebaeude-aus-24074#8)

**Comment by dunland** [comment]
Nur zum Festhalten: Energieeffizientklasse bezieht sich auf Gebäude → wird dadurch 1:1 auf Haushalte übertragen, ganz egal wie groß die WE sind und wie viele es gibt. Teilen dieses Wertes durch Anzahl WE würde zum Beispiel quatsch sein, weil ja nicht Effizienzklasse F + Effizienzklasse F = Effizienzklasse D bzw D/2 != F

**Comment by lwinkeler** [comment]
Stimmt!
Weshalb ich ebenfalls so am hadern war ist, dass wir unsere Daten natürlich wieder nicht ganz mit der Effizienzklasse abgleichen können. Hintergrund ist, dass wir ja eine Kombination aus **Gebäudezustand** und **Heizverhalten** haben. 

Verbraucherzentrale:
> Daneben hängt der reale Energieverbrauch stark vom Standort, von den Witterungsverhältnissen und dem individuellen Heizverhalten der Bewohner:innen ab. Bei einem Bedarfsausweis wird seit 2014 beim Berechnungsverfahren nach der DIN V 18599 eine durchschnittliche Raumtemperatur von 20 °C angenommen, jedes Grad darüber erhöht den Energieverbrauch um rund 6 Prozent.

Es könnte dementsprechend folgender der Schluss gezogen werden:
- MFH 200 m2, 2 Haushalte -> dementsprechend "hoher" Wärmeverbrauch
- EFH 200 m2, 1 Haushalt -> dementsprechend "niedriger" Wärmeverbrauch
- Wenn beide Häuser bspw. gleicher Bauart wären, würde unsere Skala anzeigen, dass das MFH eine schlechtere Effizienzklasse hat
- Wenn ich keinen Denkfehler habe: Wie gehen wir damit um?
  - Ignorieren und im Workshop, sollte die Frage aufkommen im Hinterkopf haben
  - Anpassung? Wenn ja, wie?

Ich struggle gerade auch noch ein wenig mit folgender Fragestellung: Abgesehen von Effekten durch's Wohnen auf engem Raum; müssten MFH nicht automatisch schlechtere Effizienzklassen auswerfen, da kleinere Wohnfläche pP kombiniert mit höherem Verbrauch, da viele Wohnhafte?

**Comment by joroeder** [comment]
> 
> Unsere Katasterdaten sind natürlich nicht verhaltensbereinigt, dass die Einstufung demnach exakt zutrifft, muss infrage gestellt werden. Für die Erstellung der Cluster dürfte es aber passen 👍

Ne, das sind sie nicht. Was du mit "verhaltensbereinigt" meinst, wäre die Erstellung eines Bedarfsausweises (das folgt einer festgelegten Berechnungsvorschrift auf Basis der Gebäude- und Dämmeigenschaften, sowie eingebaute Raumlufttechnik, Heizung, etc. ). Was man aus den Daten machen kann, wäre eine Verbrauchsausweis (siehe die Quelle von dir eben, da gibt es zwei verschiedene Ausweise.

**Comment by joroeder** [comment]
ja schwierig, vermutlich wäre es für euch cool, wenn ihr beides getrennt hättet: Bedarf und Verbrauch. Aber es liegt leider nur letzteres vor. Letztlich weiß man bei einem Haus mit hohem Verbrauch nicht genau, ob der einfach verschwenderisch heizt, oder ob das Gebäude so schelcht ist, oder beides. Wobei im Mittel der Verbrauch ja schon auch eine gute Indikation über den Gebäudezustand ist.

**Comment by lwinkeler** [comment]
Voll! In diesem Fall geht es ja eigentlich auch erstmal nur darum, einen Richtwert am Infoscreen für die Benutzer:innen des qScopes zu haben, damit sie grob einschätzen können, was bei dem ausgewählten Gebäude geht und wir eine Möglichkeit haben, das Darstellen der exakten Katasterdaten zu umgehen.
Von daher würde ich sagen: Gebäudecluster nach Energieeffizienzklassen (2014) festlegen und ab dafür. Wenn dann fragen kommen, haben wir das auf'm Schirm.

Danke übrigens für's Dazuschalten, Johannes, schön sogar ungefragt eine Meinung dazu zu bekommen 🙏 !

**Comment by joroeder** [comment]
Ja, kein Problem, hatte das gerade zufällig gesehen. Genau, am Ende müsst ihr nur wissen, dass es da diese zwei Methoden gibt, falls irgendein spitzfindiger Mensch da genauer nachfragt.

**Comment by dunland** [comment]
Zuordnung zu Energieeffizienzklassen nach spezifischem Wärmeverbrauch als grafische Anzeige... ist implementiert! :ballot_box_with_check:
