### ISSUE TITLE
Gebäude mit 0.0 building_household_expenses_heat

### ISSUE THREAD

**Issue by dunland** [quarree100/q100_abm#94]
Manche Gebäude haben durchgehend 0.0 building_household_expenses_heat.
Schaut man sich einmal die derzeitige "Referenz-Simulation" (Simulation ohne Entscheidungen, `qScope/data/precomputed/simulation_defaults/energy_prices/`) an, lässt sich bei folgenden Gebäuden eine 0-Kurve erkennen:

2.07, 2.11, 7.14, 7.20

bei 5.11 und 6.06 lässt sich der Fehler erkennen, sobald connection_to_heat_grid != False.. bei den anderen ist das nicht der Fall

ich habe versucht, den Fehler systematisch zu ermitteln und habe dabei folgende Tabelle erstellt (Datengrundlage ist Simulation in 
`Seafile/Q-Scope_data/outputs/Error_zero_building_household_expenses/output_20221024_18-11-58connect2028Refurbish` oder auch `Seafile/Q-Scope_data/outputs/Error_zero_building_household_expenses/output_20221024_18-48-17connect2021Refurbish`, die sich auch reproduzieren lässt.. stand 704ae4a48dd4cd0e10ff16e83ddf924ce9fbec4d )

id | Bemerkung | Energieträger (Kataster) | Sanierung SIZ | Kein Anschluss | Anschluss + Sanierung (output_20221024_18-48-17connect2021Refurbish) | nur Anschluss (output_20221024_18-29-20connect2028)
---|---|---|---|---|---|---
1.02 | Nachtspeicherheizung | Gas | t | Anstieg | Anstieg mit Sprung | Anstieg bis Anschluss, dann const
2.07 | Nachtspeicherheizung | **Strom** | u | **0.0** | 0.0 mit Sprung | 0.0 vor und nach Anschluss; Sprung bei Anschluss
2.11 | Nachtspeicherheizung | **Strom** | u | **0.0** | 0.0 mit Sprung | 0.0 vor und nach Anschluss; Sprung bei Anschluss
5.11 | --- | **Gas** | u | Anstieg | immer 0.0 (**Anschluss nicht vollzogen!**) | Anstieg bis Anschluss, dann const
6.06 | --- | **Gas** | u | Anstieg | immer 0.0 (**Anschluss nicht vollzogen!**) | Anstieg bis Anschluss, dann const
7.14 | Nachtspeicherheizung | **Strom** | u | **0.0** | 0.0 mit Sprung | 0.0 vor und nach Anschluss; Sprung bei Anschluss
7.20 | Nachtspeicherheizung | **Strom** | u | **0.0** | 0.0 mit Sprung | 0.0 vor und nach Anschluss; Sprung bei Anschluss

Ein schneller Blick zeigt: power_supplier scheinen bei den unterschiedlichen Simulationen immer gleich gewesen zu sein...

**Comment by dunland** [comment]
im Übrigen geht der "Sprung" bei Anschluss immer nach oben ‒ was nicht unbedingt toll ist, v.a. wenn man vorher 0 Wärmekosten hatte ;)

bitte an @lwinkeler um Übernahme! Ich denke es macht Sinn, dass du dich da weiter reinhängst

**Comment by lwinkeler** [comment]
Closed with https://github.com/lwinkeler/q100_abm_qscope-workshop/pull/14
